#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Network UPS Tools
# Ensures the configuration exists
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a CONF_FILES=("nut.conf" "ups.conf" "upsd.conf" "upsmon.conf" "upssched.conf")

# Remove clutter files
rm -rf /etc/nut/*.apk-new

# Ensure configuration exists
if ! hass.directory_exists "/config/nut/"; then
    mkdir -p /config/nut \
        || hass.die "Failed to create NUT configuration directory"

    # Copy template files
    hass.log.info "Copying config template files"
    for file in "${CONF_FILES[@]}"; do
        cp "/etc/nut/${file}" /config/nut/
    done
fi

# Replace config files with user config files
hass.log.info "Copying user config files"

# Copy user config files
cp -rf /config/nut/. /etc/nut/

# Fix permissions
chmod -R 660 /etc/nut/*
chown -R root:nut /etc/nut/*
