#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Network UPS Tools
# Run stdin listener
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare cmd
declare args

# hass.log.info "Listening for messages via stdin service call"

# Listen for stdin messages
while read -r msg; do
    hass.log.debug "${msg}"
    cmd=$(hass.jq "${msg}" ".command")
    hass.log.info "Received message with command: ${cmd}"

    case "${cmd}" in
        upsc)
            args=$(hass.jq "${msg}" ".arguments // empty")
            set -x
            # shellcheck disable=SC2086
            exec upsc ${args}
            set +x
            ;;
        dmesg)
            set -x
            exec dmesg | grep -i usb
            set +x
            ;;
        *)
            hass.log.error "Command not found: ${cmd}"
            ;;
    esac
done < /proc/1/fd/0
