---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:8.1.0
  amd64: ghcr.io/hassio-addons/debian-base:8.1.0
  armv7: ghcr.io/hassio-addons/debian-base:8.1.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
