---
name: Network UPS Tools
version: dev
slug: nut
description: Manage battery backup (UPS) devices
url: https://github.com/hassio-addons/addon-nut
codenotary: codenotary@frenck.dev
startup: system
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
uart: true
udev: true
usb: true
hassio_api: true
hassio_role: manager
homeassistant_api: true
ports:
  3493/tcp: null
ports_description:
  3493/tcp: Network UPS Tools
options:
  users:
    - username: ""
      password: ""
      instcmds:
        - all
      actions: []
  devices:
    - name: myups
      driver: usbhid-ups
      port: auto
      config: []
  mode: netserver
  shutdown_host: "false"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  users:
    - username: str
      password: password
      instcmds:
        - str
      actions:
        - str
      upsmon: list(master|slave)?
  devices:
    - name: str
      driver: str
      port: str
      powervalue: int?
      config:
        - str
  mode: list(netserver|netclient)
  shutdown_host: bool
  list_usb_devices: bool?
  remote_ups_name: str?
  remote_ups_host: str?
  remote_ups_password: password?
  remote_ups_user: str?
  upsd_maxage: int?
  upsmon_deadtime: int?
  i_like_to_be_pwned: bool?
  leave_front_door_open: bool?
